import Head from "next/head";
import React from "react";
import Header from "~/components/header";

const tree_model = () => {
    return (
        <>
            <Head>
                <title>Tree Model</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@100;400;500;700;800&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <Header />
            <main className="min-h-screen bg-stone-950 p-2 pb-16 pt-8 font-main  text-stone-300 sm:flex sm:flex-col sm:items-center sm:p-8">
                <div className="px-4 transition-all duration-200 sm:w-[600px] md:w-[700px] lg:w-[800px]">
                    <section>
                        <h1 className="mb-2 mt-2 text-center text-5xl font-bold">
                            Rubit
                        </h1>
                        <div className="py-8">
                            <h3 className="text-center text-2xl">
                                Create vocabulary lists from Russian text!
                            </h3>
                            <p className="py-2">
                                Try YouTube transcripts of podcasts or speeches,
                                book chapters, or articles.
                            </p>
                            <p className="py-2">
                                Input your study material text and choose
                                settings for what kind of list output you want.
                            </p>
                        </div>
                    </section>
                </div>
            </main>
        </>
    );
};

export default tree_model;
